version: '3.7'

services:
  twitterApi:
    image: baselzockt/twitterapi
    restart: on-failure
    networks:
      - activemqgo
    environment:
      - "ENDPOINT=activemq:61613"


networks:
  activemqgo:
    external:
      name: activemqgo